### ISSUE TITLE
download_toolkit temp file should be a generated location and just be the toolkit.

### ISSUE THREAD

**Issue by markheger** [IBMStreams/pypi.streamsx.toolkits#3]
https://github.com/IBMStreams/pypi.streamsx.endpoint/issues/10

**Comment by ghost** [comment]
The generated toolkit location with the random token should apply only when no target directory is given for the downloaded toolkit. When a target directory is given, i.e. `target_dir` being NOT `None`, the user would expect that the downloaded toolkit goes into the specified directory and not into `target_dir + '-' + <some random>`.
```
def download_toolkit(toolkit_name, repository_name=None, url=None, target_dir=None):
```
